name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6 # or alternative dependency management
      - uses: php-actions/phpunit@v3
      - name: Check version of installed PHPUnit
        run: |
          php ./vendor/bin/phpunit --version
      - name: Test all test cases
        run: |
          sudo php ./vendor/bin/phpunit --do-not-cache-result