name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: learn_phpunit
          MYSQL_USER: app_user
          MYSQL_PASSWORD: root12345678
          MYSQL_ROOT_PASSWORD: root12345678
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6 # or alternative dependency management
      - uses: php-actions/phpunit@v3
      - name: Set up MySQL
        run: |
          sudo /etc/init.d/mysql start
      - name: Write DB Config in env test local
        run: |
          cp .env .env.local && echo "DATABASE_URL=\"mysql://app_user:root12345678@127.0.0.1:3306/learn_phpunit?serverVersion=8&charset=utf8mb4\"" >> .env.local
          cp .env.test .env.test.local && echo "DATABASE_URL=\"mysql://app_user:root12345678@127.0.0.1:3306/learn_phpunit?serverVersion=8&charset=utf8mb4\"" >> .env.test.local
      - name: Create db and run migrations
        run: |
          php bin/console doctrine:migration:migrate --no-interaction
      - name: Check version of installed PHPUnit
        run: |
          php ./vendor/bin/phpunit --version
      - name: Test all test cases
        run: |
          sudo php ./vendor/bin/phpunit --do-not-cache-result